### ISSUE TITLE
DEPRECATION: A property of <xamoom-customer@view:-outlet::ember1023> was modified inside the didInsertElement hook.

### ISSUE THREAD

**Issue by xamoom-pali** [indexiatech/ember-idx-tabs#22]
DEPRECATION: A property of <xamoom-customer@view:-outlet::ember1023> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16463:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16371:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16463:7)
        at invoke (http://localhost:4200/assets/vendor.js:16479:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16432:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26471:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/assets/vendor.js:53728:22)
        at http://localhost:4200/assets/vendor.js:23984:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/assets/vendor.js:32379:11)

DEBUG: 
Ember             : 2.5.1
Ember Data    : 2.5.2
jQuery             : 2.2.3

**Comment by patgod85** [comment]
+1
